import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Hotstar Disney ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <Header>
            {children}
            <h1
              className={`text-sm font-medium px-10 py-4 text-gray-600 w-full text-center `}
            >
              This Website for educational purpose only. We do not store any
              data on our server.
            </h1>
          </Header>
        </ThemeProvider>
      </body>
    </html>
  );
}
